#!/bin/bash

cd /usr/local/mysql

scripts/mysql_install_db --user=mysql

bin/mysqld_safe --user=mysql &
# Copyright - Carlos Montalvo 2015
# You may freely distribute this file but please keep my name in here
# as the original owner
